# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Mrdai\Programming\PyCharm Project2-2017\Eric6\SerialDebug\mainFrame.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SerialTest(object):
    def setupUi(self, SerialTest):
        SerialTest.setObjectName("SerialTest")
        SerialTest.resize(607, 544)
        self.centralWidget = QtWidgets.QWidget(SerialTest)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 591, 81))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 19, 591, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox_3 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_3)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.scanButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.scanButton.setObjectName("scanButton")
        self.horizontalLayout.addWidget(self.scanButton)
        self.openButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.closeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 591, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 591, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.sendButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout.addWidget(self.sendButton, 0, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 250, 591, 261))
        self.groupBox_3.setObjectName("groupBox_3")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollArea.setGeometry(QtCore.QRect(0, 20, 591, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 589, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textArea = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textArea.setGeometry(QtCore.QRect(0, 0, 591, 181))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.textArea.setFont(font)
        self.textArea.setAcceptDrops(True)
        self.textArea.setUndoRedoEnabled(True)
        self.textArea.setReadOnly(True)
        self.textArea.setObjectName("textArea")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 200, 591, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.cleanButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.cleanButton.setObjectName("cleanButton")
        self.horizontalLayout_2.addWidget(self.cleanButton)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.statuslabel = QtWidgets.QLabel(self.centralWidget)
        self.statuslabel.setGeometry(QtCore.QRect(10, 520, 581, 16))
        self.statuslabel.setObjectName("statuslabel")
        SerialTest.setCentralWidget(self.centralWidget)

        self.retranslateUi(SerialTest)
        self.comboBox_2.setCurrentIndex(1)
        self.comboBox_3.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(SerialTest)

    def retranslateUi(self, SerialTest):
        _translate = QtCore.QCoreApplication.translate
        SerialTest.setWindowTitle(_translate("SerialTest", "SerialTest"))
        self.groupBox.setTitle(_translate("SerialTest", "Setup"))
        self.label.setText(_translate("SerialTest", "串口号"))
        self.label_3.setText(_translate("SerialTest", "波特率"))
        self.comboBox_2.setItemText(0, _translate("SerialTest", "4800"))
        self.comboBox_2.setItemText(1, _translate("SerialTest", "9600"))
        self.comboBox_2.setItemText(2, _translate("SerialTest", "14400"))
        self.comboBox_2.setItemText(3, _translate("SerialTest", "19200"))
        self.comboBox_2.setItemText(4, _translate("SerialTest", "38400"))
        self.comboBox_2.setItemText(5, _translate("SerialTest", "56000"))
        self.label_4.setText(_translate("SerialTest", "数据位"))
        self.comboBox_3.setItemText(0, _translate("SerialTest", "5"))
        self.comboBox_3.setItemText(1, _translate("SerialTest", "6"))
        self.comboBox_3.setItemText(2, _translate("SerialTest", "7"))
        self.comboBox_3.setItemText(3, _translate("SerialTest", "8"))
        self.scanButton.setText(_translate("SerialTest", "扫描串口"))
        self.openButton.setText(_translate("SerialTest", "打开串口"))
        self.closeButton.setText(_translate("SerialTest", "关闭串口"))
        self.groupBox_2.setTitle(_translate("SerialTest", "Send"))
        self.sendButton.setText(_translate("SerialTest", "发送数据"))
        self.checkBox.setText(_translate("SerialTest", "Hex"))
        self.groupBox_3.setTitle(_translate("SerialTest", "Receive"))
        self.textArea.setHtml(_translate("SerialTest", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:12pt;\"><br /></p></body></html>"))
        self.cleanButton.setText(_translate("SerialTest", "清除窗口"))
        self.checkBox_2.setText(_translate("SerialTest", "Hex显示"))
        self.statuslabel.setText(_translate("SerialTest", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SerialTest = QtWidgets.QMainWindow()
    ui = Ui_SerialTest()
    ui.setupUi(SerialTest)
    SerialTest.show()
    sys.exit(app.exec_())

